server.port=8085

server.error.whitelabel.enabled=false



#Lazy relations CANNOT load
#If code tries to access them ? Hibernate throws LazyInitializationException
#Jackson serializer cannot load lazy fields
#DTO mappers cannot accidentally access lazy relations
#You get ONLY the fields you fetched
spring.jpa.open-in-view=false



spring.datasource.url= jdbc:mysql://localhost:3306/sms
#spring.datasource.url= jdbc:mysql://db:3306/students
spring.datasource.username= root
spring.datasource.password= rootpassword123



# Flyway settings (optional)
#spring.flyway.baseline-on-migrate=true
#spring.flyway.locations=classpath:db/migration


# Disable automatic schema generation
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
spring.datasource.retry-attempts=5
spring.datasource.retry-delay=5s

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect



# application.properties
spring.security.userEntity.name=Admin
spring.security.userEntity.password=Admin123

jwt.secret=mySuperSecretKeyForJWTThatIsAtLeast32CharsLong
jwt.expirationTime=36000000


##########################################################################
#           JWT
##########################################################################
jwt.private.key = v9R8zKpYVX1R2QXtZfE3a9q4dR1kPZsxA8d4FOTKW2aHq0qzR9xL5lKuvxF93J6r4K7a9zP1yW8dT0mvQ2u3sw==
jwt.audience = EE3CC1F6AB392EBBEAC1DB1F41C74
jwt.issuer = D6A4957A21FA51EA945AE9C958E95
jwt.expiry=90000000
jwt.refresh.token.expiry=6000000
jwt.cookie.name=SMS

# Charge Types
fee.charge-types.FIXED=Fixed Amount
fee.charge-types.PERCENTAGE=Percentage
fee.charge-types.PER_CREDIT=Per Credit
fee.charge-types.PER_SUBJECT=Per Subject
fee.charge-types.VARIABLE=Variable
fee.charge-types.SLAB_BASED=Slab Based
fee.charge-types.USAGE_BASED=Usage Based
fee.charge-types.DISCOUNTED=Discounted

# Recurrence Rules
fee.recurrence-rules.ONE_TIME=One Time
fee.recurrence-rules.MONTHLY=Monthly
fee.recurrence-rules.QUARTERLY=Quarterly
fee.recurrence-rules.BI_MONTHLY=Bi-Monthly
fee.recurrence-rules.HALF_YEARLY=Half-Yearly
fee.recurrence-rules.YEARLY=Yearly
fee.recurrence-rules.TERM_WISE=Term Wise
fee.recurrence-rules.SEMESTER_WISE=Semester Wise


# Blood Groups
blood.group.A_POSITIVE=A+
blood.group.A_NEGATIVE=A-
blood.group.B_POSITIVE=B+
blood.group.B_NEGATIVE=B-
blood.group.AB_POSITIVE=AB+
blood.group.AB_NEGATIVE=AB-
blood.group.O_POSITIVE=O+
blood.group.O_NEGATIVE=O-



# Nationality
nationality.map.PAKISTANI=Pakistani
nationality.map.AFGHAN=Afghan
nationality.map.INDIAN=Indian
nationality.map.IRANIAN=Iranian
nationality.map.CHINESE=Chinese
nationality.map.ARAB=Arab
nationality.map.EUROPEAN=British/European
nationality.map.OTHER=Other


# Religion
religion.list.ISLAM=Islam
religion.list.CHRISTIANITY=Christianity
religion.list.HINDUISM=Hinduism
religion.list.SIKHISM=Sikhism
religion.list.ZOROASTRIAN=Zoroastrianism
religion.list.BUDDHISM=Buddhism
religion.list.OTHER=Other / None
