-- Board Member Roles Table
CREATE TABLE board_member_roles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by BIGINT,
    deleted_at DATETIME,
    deleted_by BIGINT,
    UNIQUE KEY uq_role_code_org (code, organization_id),
    CONSTRAINT fk_board_member_roles_org FOREIGN KEY (organization_id) REFERENCES institutes(id)
);

-- Seed Data for Board Member Roles
INSERT INTO board_member_roles (organization_id, code, name) VALUES
(1, 'CHAIRMAN', 'Chairman'),
(1, 'CHAIRPERSON', 'Chairperson'),
(1, 'PRESIDENT', 'President'),
(1, 'VICE_CHAIRMAN', 'Vice Chairman'),
(1, 'VICE_CHAIRPERSON', 'Vice Chairperson'),
(1, 'VICE_PRESIDENT', 'Vice President'),
(1, 'DIRECTOR', 'Board Director'),
(1, 'EXECUTIVE_DIRECTOR', 'Executive Director'),
(1, 'NON_EXECUTIVE_DIRECTOR', 'Non-Executive Director'),
(1, 'INDEPENDENT_DIRECTOR', 'Independent Director'),
(1, 'ADVISOR', 'Advisor'),
(1, 'TRUSTEE', 'Trustee'),
(1, 'GOVERNOR', 'Governor'),
(1, 'BOARD_MEMBER', 'Board Member'),
(1, 'SECRETARY', 'Board Secretary'),
(1, 'ASSISTANT_SECRETARY', 'Assistant Secretary'),
(1, 'TREASURER', 'Treasurer'),
(1, 'ASSISTANT_TREASURER', 'Assistant Treasurer'),
(1, 'CHANCELLOR', 'Chancellor'),
(1, 'VICE_CHANCELLOR', 'Vice Chancellor'),
(1, 'PRO_CHANCELLOR', 'Pro Chancellor'),
(1, 'RECTOR', 'Rector'),
(1, 'PROVOST', 'Provost'),
(1, 'AUDIT_COMMITTEE_MEMBER', 'Audit Committee Member'),
(1, 'FINANCE_COMMITTEE_MEMBER', 'Finance Committee Member'),
(1, 'ACADEMIC_COMMITTEE_MEMBER', 'Academic Committee Member'),
(1, 'GOVERNANCE_COMMITTEE_MEMBER', 'Governance Committee Member'),
(1, 'LEGAL_ADVISOR', 'Legal Advisor'),
(1, 'FINANCIAL_ADVISOR', 'Financial Advisor'),
(1, 'STRATEGIC_ADVISOR', 'Strategic Advisor'),
(1, 'EXTERNAL_MEMBER', 'External Board Member'),
(1, 'INTERNAL_MEMBER', 'Internal Board Member'),
(1, 'PATRON', 'Patron'),
(1, 'FOUNDER', 'Founder'),
(1, 'CO_FOUNDER', 'Co-Founder'),
(1, 'HONORARY_MEMBER', 'Honorary Member');
