name: CI

on:
  push:
    branches:
      - origin/develop
      - origin/uat
      - origin/prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: echo "Building application..."
