name: CI

on:
  push:
    branches:
      - develop
      - uat
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: echo "Building application..."
